apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: 810197524-810196656
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2000M
  storageClassName: hiops
  volumeMode: Filesystem
